apiVersion: v1
kind: Service
metadata:
  name: {{ include "spire-registrar.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spire-registrar.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  selector:
    {{- include "spire-registrar.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
